baseURL = 'https://r-amos.github.io/tvivl'
languageCode = 'en-us'
theme = 'hyde'
title = 'tvivl'
disqusShortname = 'tvivl'
[params]
  description = "Learnings from adventures in software development."
  layoutReverse = false
  themeColor = "theme-base-0h"
[Menus]
  main = [
      {Name = "linkedin", URL = "https://www.linkedin.com/in/rob-amos-9a7a7a130/"},
  ]
